services:
  siem:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend/logs:/app/logs  # mount log asli dari host (opsional)
    restart: unless-stopped
