sonar.projectKey=siem-dashboard
sonar.projectName=SIEM Dashboard
sonar.projectVersion=1.0

sonar.sources=backend/app
sonar.tests=backend/tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,backend/logs/**,frontend/**,**/.pytest_cache/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=backend/app/main.py,backend/app/db/database.py,backend/app/core/log_collector.py,backend/app/api/websocket.py,backend/app/api/routes.py

sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S7484
sonar.issue.ignore.multicriteria.e1.resourceKey=backend/app/core/log_collector.py
